import { useNavigate } from 'react-router-dom'
import VersionDisplay from './VersionDisplay'
import './AboutPage.css'

type LanguageMode = 'chinese' | 'english'

interface AboutPageProps {
  languageMode: LanguageMode
}

const AboutPage = ({ languageMode }: AboutPageProps) => {
  const navigate = useNavigate()

  const translations = {
    chinese: {
      title: '关于本应用',
      back: '← 返回',
      subtitle: '荷兰语单词学习',
      description: '一个帮助您学习荷兰语单词的互动学习工具',
      disclaimerTitle: '免责声明',
      disclaimer: '本应用的大部分单词内容（包括翻译、例句等）由人工智能（AI）自动生成。虽然我们尽力确保内容的准确性，但AI生成的内容可能存在错误或不准确之处。请用户在使用时注意甄别，如有疑问请参考权威的荷兰语词典或学习资料。',
      featuresTitle: '主要功能',
      features: [
        '单词卡片学习：翻转卡片查看单词详情和例句',
        '语音发音：点击发音按钮听取荷兰语发音',
        '学习进度跟踪：记录您的学习进度和掌握程度',
        '测试功能：通过测试检验学习成果',
        '拼写游戏：趣味拼写练习巩固记忆',
        '单词表：快速浏览和管理所有单词'
      ],
      contactTitle: '联系我们',
      feedback: '如果您发现内容错误或有任何建议，欢迎反馈。',
      issueLink: '提问题 / 提建议',
      thanks: '感谢使用荷兰语单词学习应用！'
    },
    english: {
      title: 'About',
      back: '← Back',
      subtitle: 'Dutch Word Learning',
      description: 'An interactive learning tool to help you learn Dutch vocabulary',
      disclaimerTitle: 'Disclaimer',
      disclaimer: 'Most of the word content in this app (including translations, examples, etc.) is automatically generated by artificial intelligence (AI). While we strive to ensure accuracy, AI-generated content may contain errors or inaccuracies. Please use your judgment when using this app, and refer to authoritative Dutch dictionaries or learning materials for verification if you have any doubts.',
      featuresTitle: 'Key Features',
      features: [
        'Flashcard learning: Flip cards to view word details and examples',
        'Audio pronunciation: Click the pronunciation button to hear Dutch pronunciation',
        'Progress tracking: Track your learning progress and mastery level',
        'Quiz feature: Test your knowledge through quizzes',
        'Spelling game: Fun spelling practice to reinforce memory',
        'Word list: Quickly browse and manage all words'
      ],
      contactTitle: 'Contact Us',
      feedback: 'If you find any content errors or have suggestions, please feel free to provide feedback.',
      issueLink: 'Submit Issue / Suggestion',
      thanks: 'Thank you for using the Dutch Word Learning app!'
    }
  }

  const t = translations[languageMode]

  return (
    <div className="about-page">
      <div className="about-container">
        <button
          className="back-button"
          onClick={() => navigate(`/${languageMode === 'chinese' ? 'zh' : 'en'}/learn`)}
        >
          {t.back}
        </button>

        <h1 className="about-title">{t.title}</h1>

        <div className="about-content">
          <div className="about-section">
            <h2 className="about-subtitle">{t.subtitle}</h2>
            <p className="about-description">{t.description}</p>
          </div>

          <div className="about-section disclaimer-section">
            <h2 className="section-title">{t.disclaimerTitle}</h2>
            <p className="disclaimer-text">{t.disclaimer}</p>
          </div>

          <div className="about-section">
            <h2 className="section-title">{t.featuresTitle}</h2>
            <ul className="features-list">
              {t.features.map((feature, index) => (
                <li key={index} className="feature-item">
                  <span className="feature-bullet">✓</span>
                  <span>{feature}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="about-section">
            <h2 className="section-title">{t.contactTitle}</h2>
            <p className="about-description">{t.feedback}</p>
            <a
              href="https://github.com/lafengxiaoyu/nl-words/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="issue-link"
            >
              {t.issueLink} →
            </a>
          </div>

          <div className="about-footer">
            <p className="thanks-text">{t.thanks}</p>
            <VersionDisplay languageMode={languageMode} position="footer" />
          </div>
        </div>
      </div>
    </div>
  )
}

export default AboutPage
